// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hijjzwocglzmbaqznxfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpamp6d29jZ2x6bWJhcXpueGZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwMTAzMzYsImV4cCI6MjA4OTU4NjMzNn0.0rGuZmvOTU1iEieEO6oTipfbSrCO2_q5VD_QGDDbGog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});